# Generated by Django 4.2.7 on 2023-11-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardiacData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('septo_e', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('septo_e_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('diastole_septo_iv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diastole_septo_iv_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('ventriculo_esq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ventriculo_esq_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('rec_date', models.DateTimeField(verbose_name='record date published')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rec_date', models.DateTimeField(verbose_name='record date published')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rec_date', models.DateTimeField(verbose_name='record date published')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartcaresite.owner')),
            ],
        ),
        migrations.CreateModel(
            name='CardiacMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('cardiac_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartcaresite.cardiacdata')),
            ],
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heartcaresite.pet'),
        ),
    ]
