# Generated by Django 4.2.7 on 2023-11-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='fup_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='follow up date'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='rec_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='record date published'),
        ),
    ]
