# Generated by Django 4.2.7 on 2023-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0002_owner_address_owner_email_owner_phone_pet_fup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight_kg',
            field=models.CharField(max_length=255),
        ),
    ]
