# Generated by Django 4.2.7 on 2023-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0004_alter_pet_breed_alter_pet_gender_alter_pet_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiacdata',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
