# Generated by Django 4.2.7 on 2023-11-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0005_cardiacdata_conclusion_cardiacdata_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiacdata',
            name='diastole_septo_iv',
        ),
        migrations.RemoveField(
            model_name='cardiacdata',
            name='diastole_septo_iv_unit',
        ),
        migrations.RemoveField(
            model_name='cardiacdata',
            name='septo_e',
        ),
        migrations.RemoveField(
            model_name='cardiacdata',
            name='septo_e_unit',
        ),
        migrations.RemoveField(
            model_name='cardiacdata',
            name='ventriculo_esq',
        ),
        migrations.RemoveField(
            model_name='cardiacdata',
            name='ventriculo_esq_unit',
        ),
    ]
