# Generated by Django 4.2.7 on 2023-11-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0006_remove_cardiacdata_diastole_septo_iv_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardiacMeasurement',
        ),
    ]
