# Generated by Django 4.2.7 on 2023-11-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0007_delete_cardiacmeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiacdata',
            name='description',
        ),
    ]
