# Generated by Django 4.2.7 on 2023-11-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0008_remove_cardiacdata_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiacdata',
            name='report_date',
        ),
    ]
