# Generated by Django 4.2.7 on 2023-12-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0009_remove_cardiacdata_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10)),
                ('weight_metric', models.CharField(max_length=255)),
                ('min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
