# Generated by Django 4.2.7 on 2023-12-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0010_tapse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiacdata',
            name='dia_sist_ve',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='diad_interno_ve_diast_norm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='diam_ae',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='diam_aortico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='diam_atrio_ao_esq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='diast_diad_ve',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='diast_par_post_ve',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='diastole_septo_iv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='encurtamento_frac_VE',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='frac_ejecao',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='gp_max_va',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='gradiente_pico_pulmonar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='onda_a_lateral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='onda_e_lateral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='razao_ee_lat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='tapse',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='tapse_resultado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='taxa_mitral_e_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='temp_desacel_onda_e_mitral',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='temp_relax_isovol_e_mitral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='temp_relax_isovol_mitral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='vel_pico_pulmonar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='vel_pico_va',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='veloc_pico_mit_ond_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cardiacdata',
            name='veloc_pico_mit_onda_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
