# Generated by Django 4.2.7 on 2023-12-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0011_cardiacdata_dia_sist_ve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiacdata',
            name='diam_ae',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardiacdata',
            name='diam_aortico',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
