# Generated by Django 4.2.7 on 2023-12-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0012_alter_cardiacdata_diam_ae_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
