# Generated by Django 4.2.7 on 2023-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0013_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiacdata',
            name='weight_kg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
