# Generated by Django 4.2.7 on 2023-12-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartcaresite', '0014_cardiacdata_weight_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiacdata',
            old_name='weight_kg',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
